[{"authorTime":"2019-08-16 20:51:17","codes":[{"authorDate":"2019-08-16 20:51:17","commitOrder":1,"curCode":"    public void assertError2() {\n        TestSubscriber<Integer> ts = TestSubscriber.create();\n\n        try {\n            ts.assertError(TestException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertError(new TestException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysTrue());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertSubscribed();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.onSubscribe(new BooleanSubscription());\n\n        ts.assertSubscribed();\n\n        ts.assertNoErrors();\n\n        TestException ex = new TestException(\"Forced failure\");\n\n        ts.onError(ex);\n\n        ts.assertError(ex);\n\n        ts.assertError(TestException.class);\n\n        ts.assertError(Functions.<Throwable>alwaysTrue());\n\n        ts.assertError(new Predicate<Throwable>() {\n            @Override\n            public boolean test(Throwable t) {\n                return t.getMessage() != null && t.getMessage().contains(\"Forced\");\n            }\n        });\n\n        try {\n            ts.assertError(new RuntimeException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(IOException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertNoErrors();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysFalse());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.assertValueCount(0);\n\n        ts.assertNoValues();\n    }\n","date":"2019-08-16 20:51:17","endLine":835,"groupId":"1951","id":1,"instanceNumber":1,"isCurCommit":0,"methodName":"assertError2","params":"()","path":"/mnt/clonedata/CloneManagementServer/ManagementServer/consistResult/result-rxjava-10-0.7/blobInfo/CC_OUT/blobs/33/d95bea88700928dd4fea5f61ce911ae6c7a0c4.src","preCode":"    public void assertError2() {\n        TestSubscriber<Integer> ts = TestSubscriber.create();\n\n        try {\n            ts.assertError(TestException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertError(new TestException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysTrue());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertSubscribed();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.onSubscribe(new BooleanSubscription());\n\n        ts.assertSubscribed();\n\n        ts.assertNoErrors();\n\n        TestException ex = new TestException(\"Forced failure\");\n\n        ts.onError(ex);\n\n        ts.assertError(ex);\n\n        ts.assertError(TestException.class);\n\n        ts.assertError(Functions.<Throwable>alwaysTrue());\n\n        ts.assertError(new Predicate<Throwable>() {\n            @Override\n            public boolean test(Throwable t) {\n                return t.getMessage() != null && t.getMessage().contains(\"Forced\");\n            }\n        });\n\n        try {\n            ts.assertError(new RuntimeException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(IOException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertNoErrors();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysFalse());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.assertValueCount(0);\n\n        ts.assertNoValues();\n    }\n","realPath":"src/test/java/io/reactivex/rxjava3/subscribers/TestSubscriberTest.java","repoName":"rxjava","snippetEndLine":0,"snippetStartLine":0,"startLine":750,"status":"B"},{"authorDate":"2019-08-16 20:51:17","commitOrder":1,"curCode":"    public void assertError2() {\n        TestSubscriberEx<Integer> ts = new TestSubscriberEx<Integer>();\n\n        try {\n            ts.assertError(TestException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertError(new TestException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertErrorMessage(\"\");\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysTrue());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertSubscribed();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertTerminated();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.onSubscribe(new BooleanSubscription());\n\n        ts.assertSubscribed();\n\n        ts.assertNoErrors();\n\n        TestException ex = new TestException(\"Forced failure\");\n\n        ts.onError(ex);\n\n        ts.assertError(ex);\n\n        ts.assertError(TestException.class);\n\n        ts.assertErrorMessage(\"Forced failure\");\n\n        ts.assertError(Functions.<Throwable>alwaysTrue());\n\n        ts.assertError(new Predicate<Throwable>() {\n            @Override\n            public boolean test(Throwable t) {\n                return t.getMessage() != null && t.getMessage().contains(\"Forced\");\n            }\n        });\n\n        try {\n            ts.assertErrorMessage(\"\");\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(new RuntimeException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(IOException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertNoErrors();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysFalse());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.assertTerminated();\n\n        ts.assertValueCount(0);\n\n        ts.assertNoValues();\n    }\n","date":"2019-08-16 20:51:17","endLine":903,"groupId":"1951","id":2,"instanceNumber":2,"isCurCommit":0,"methodName":"assertError2","params":"()","path":"/mnt/clonedata/CloneManagementServer/ManagementServer/consistResult/result-rxjava-10-0.7/blobInfo/CC_OUT/blobs/24/a9e84c9b5c431cf94ae9617da86de9d5828e95.src","preCode":"    public void assertError2() {\n        TestSubscriberEx<Integer> ts = new TestSubscriberEx<Integer>();\n\n        try {\n            ts.assertError(TestException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertError(new TestException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertErrorMessage(\"\");\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysTrue());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertSubscribed();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertTerminated();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.onSubscribe(new BooleanSubscription());\n\n        ts.assertSubscribed();\n\n        ts.assertNoErrors();\n\n        TestException ex = new TestException(\"Forced failure\");\n\n        ts.onError(ex);\n\n        ts.assertError(ex);\n\n        ts.assertError(TestException.class);\n\n        ts.assertErrorMessage(\"Forced failure\");\n\n        ts.assertError(Functions.<Throwable>alwaysTrue());\n\n        ts.assertError(new Predicate<Throwable>() {\n            @Override\n            public boolean test(Throwable t) {\n                return t.getMessage() != null && t.getMessage().contains(\"Forced\");\n            }\n        });\n\n        try {\n            ts.assertErrorMessage(\"\");\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(new RuntimeException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(IOException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertNoErrors();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysFalse());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.assertTerminated();\n\n        ts.assertValueCount(0);\n\n        ts.assertNoValues();\n    }\n","realPath":"src/test/java/io/reactivex/rxjava3/testsupport/TestSubscriberExTest.java","repoName":"rxjava","snippetEndLine":0,"snippetStartLine":0,"startLine":793,"status":"B"}],"commitId":"a1693ecc9215027a7a3eae75272979ebb4d79a27","commitMessage":"@@@3.x: Refactor to io.reactivex.rxjava3.** (#6621)\n\n* 3.x: Refactor to io.reactivex.rxjava3.**\n\n* fix javadoc cleanup gradle\n\n* javadoc gradle again\n\n* Fix package location in text\n","date":"2019-08-16 20:51:17","modifiedFileCount":"0","status":"B","submitter":"David Karnok"},{"authorTime":"2019-12-22 19:17:37","codes":[{"authorDate":"2019-08-16 20:51:17","commitOrder":2,"curCode":"    public void assertError2() {\n        TestSubscriber<Integer> ts = TestSubscriber.create();\n\n        try {\n            ts.assertError(TestException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertError(new TestException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysTrue());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertSubscribed();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.onSubscribe(new BooleanSubscription());\n\n        ts.assertSubscribed();\n\n        ts.assertNoErrors();\n\n        TestException ex = new TestException(\"Forced failure\");\n\n        ts.onError(ex);\n\n        ts.assertError(ex);\n\n        ts.assertError(TestException.class);\n\n        ts.assertError(Functions.<Throwable>alwaysTrue());\n\n        ts.assertError(new Predicate<Throwable>() {\n            @Override\n            public boolean test(Throwable t) {\n                return t.getMessage() != null && t.getMessage().contains(\"Forced\");\n            }\n        });\n\n        try {\n            ts.assertError(new RuntimeException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(IOException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertNoErrors();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysFalse());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.assertValueCount(0);\n\n        ts.assertNoValues();\n    }\n","date":"2019-08-16 20:51:17","endLine":835,"groupId":"108126","id":3,"instanceNumber":1,"isCurCommit":0,"methodName":"assertError2","params":"()","path":"/mnt/clonedata/CloneManagementServer/ManagementServer/consistResult/result-rxjava-10-0.7/blobInfo/CC_OUT/blobs/33/d95bea88700928dd4fea5f61ce911ae6c7a0c4.src","preCode":"    public void assertError2() {\n        TestSubscriber<Integer> ts = TestSubscriber.create();\n\n        try {\n            ts.assertError(TestException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertError(new TestException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysTrue());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertSubscribed();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.onSubscribe(new BooleanSubscription());\n\n        ts.assertSubscribed();\n\n        ts.assertNoErrors();\n\n        TestException ex = new TestException(\"Forced failure\");\n\n        ts.onError(ex);\n\n        ts.assertError(ex);\n\n        ts.assertError(TestException.class);\n\n        ts.assertError(Functions.<Throwable>alwaysTrue());\n\n        ts.assertError(new Predicate<Throwable>() {\n            @Override\n            public boolean test(Throwable t) {\n                return t.getMessage() != null && t.getMessage().contains(\"Forced\");\n            }\n        });\n\n        try {\n            ts.assertError(new RuntimeException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(IOException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertNoErrors();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysFalse());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.assertValueCount(0);\n\n        ts.assertNoValues();\n    }\n","realPath":"src/test/java/io/reactivex/rxjava3/subscribers/TestSubscriberTest.java","repoName":"rxjava","snippetEndLine":0,"snippetStartLine":0,"startLine":750,"status":"N"},{"authorDate":"2019-12-22 19:17:37","commitOrder":2,"curCode":"    public void assertError2() {\n        TestSubscriberEx<Integer> ts = new TestSubscriberEx<>();\n\n        try {\n            ts.assertError(TestException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertError(new TestException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertErrorMessage(\"\");\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysTrue());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertSubscribed();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertTerminated();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.onSubscribe(new BooleanSubscription());\n\n        ts.assertSubscribed();\n\n        ts.assertNoErrors();\n\n        TestException ex = new TestException(\"Forced failure\");\n\n        ts.onError(ex);\n\n        ts.assertError(ex);\n\n        ts.assertError(TestException.class);\n\n        ts.assertErrorMessage(\"Forced failure\");\n\n        ts.assertError(Functions.<Throwable>alwaysTrue());\n\n        ts.assertError(new Predicate<Throwable>() {\n            @Override\n            public boolean test(Throwable t) {\n                return t.getMessage() != null && t.getMessage().contains(\"Forced\");\n            }\n        });\n\n        try {\n            ts.assertErrorMessage(\"\");\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(new RuntimeException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(IOException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertNoErrors();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysFalse());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.assertTerminated();\n\n        ts.assertValueCount(0);\n\n        ts.assertNoValues();\n    }\n","date":"2019-12-22 19:17:37","endLine":903,"groupId":"108126","id":4,"instanceNumber":2,"isCurCommit":0,"methodName":"assertError2","params":"()","path":"/mnt/clonedata/CloneManagementServer/ManagementServer/consistResult/result-rxjava-10-0.7/blobInfo/CC_OUT/blobs/30/8c10e0413d5220f182cb7742884885f3b2a774.src","preCode":"    public void assertError2() {\n        TestSubscriberEx<Integer> ts = new TestSubscriberEx<Integer>();\n\n        try {\n            ts.assertError(TestException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertError(new TestException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertErrorMessage(\"\");\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysTrue());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError ex) {\n            \r\n        }\n\n        try {\n            ts.assertSubscribed();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertTerminated();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.onSubscribe(new BooleanSubscription());\n\n        ts.assertSubscribed();\n\n        ts.assertNoErrors();\n\n        TestException ex = new TestException(\"Forced failure\");\n\n        ts.onError(ex);\n\n        ts.assertError(ex);\n\n        ts.assertError(TestException.class);\n\n        ts.assertErrorMessage(\"Forced failure\");\n\n        ts.assertError(Functions.<Throwable>alwaysTrue());\n\n        ts.assertError(new Predicate<Throwable>() {\n            @Override\n            public boolean test(Throwable t) {\n                return t.getMessage() != null && t.getMessage().contains(\"Forced\");\n            }\n        });\n\n        try {\n            ts.assertErrorMessage(\"\");\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(new RuntimeException());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(IOException.class);\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertNoErrors();\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        try {\n            ts.assertError(Functions.<Throwable>alwaysFalse());\n            throw new RuntimeException(\"Should have thrown\");\n        } catch (AssertionError exc) {\n            \r\n        }\n\n        ts.assertTerminated();\n\n        ts.assertValueCount(0);\n\n        ts.assertNoValues();\n    }\n","realPath":"src/test/java/io/reactivex/rxjava3/testsupport/TestSubscriberExTest.java","repoName":"rxjava","snippetEndLine":0,"snippetStartLine":0,"startLine":793,"status":"M"}],"commitId":"0bd2a0152b64723ac3daf3e2fbad3d59c7f3bbb8","commitMessage":"@@@diamond operators in unit tests.  small packages (#6789)\n\n","date":"2019-12-22 19:17:37","modifiedFileCount":"106","status":"M","submitter":"Dmitry Volkov"}]
